name: client
description: The client application of my diploma thesis project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  either_dart: ^0.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  protobuf: ^2.0.0
  provider: ^5.0.0
  tuple: ^2.0.0
  uuid: ^3.0.4
  web_socket_channel: ^2.1.0
  xml: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  uses-material-design: true
