env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules:
  quotes: [1, 'single']
