env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - src/pb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules:
  indent: ['warn', 2]
  quotes: ['warn', 'single']
  semi: ['warn', 'always']
  '@typescript-eslint/no-non-null-assertion': off
